
name: Build Minecraft Launcher

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Electron app
      run: npm run build
      
    - name: Package app
      run: npm run package
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: minecraft-launcher-${{ matrix.os }}
        path: |
          dist/
          out/
    